| Name                             | Type                                                           | Slot | Offset | Bytes | Contract                                                                              |
|----------------------------------|----------------------------------------------------------------|------|--------|-------|---------------------------------------------------------------------------------------|
| _initialized                     | uint8                                                          | 0    | 0      | 1     | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _initializing                    | bool                                                           | 0    | 1      | 1     | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| __gap                            | uint256[50]                                                    | 1    | 0      | 1600  | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| __gap                            | uint256[50]                                                    | 51   | 0      | 1600  | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _roles                           | mapping(bytes32 => struct AccessControlUpgradeable.RoleData)   | 101  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| __gap                            | uint256[49]                                                    | 102  | 0      | 1568  | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _roleMembers                     | mapping(bytes32 => struct EnumerableSetUpgradeable.AddressSet) | 151  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| __gap                            | uint256[49]                                                    | 152  | 0      | 1568  | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _balances                        | mapping(address => uint256)                                    | 201  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _allowances                      | mapping(address => mapping(address => uint256))                | 202  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _totalSupply                     | uint256                                                        | 203  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _name                            | string                                                         | 204  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _symbol                          | string                                                         | 205  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| __gap                            | uint256[45]                                                    | 206  | 0      | 1440  | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _HASHED_NAME                     | bytes32                                                        | 251  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _HASHED_VERSION                  | bytes32                                                        | 252  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| __gap                            | uint256[50]                                                    | 253  | 0      | 1600  | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _nonces                          | mapping(address => struct CountersUpgradeable.Counter)         | 303  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _PERMIT_TYPEHASH_DEPRECATED_SLOT | bytes32                                                        | 304  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| __gap                            | uint256[49]                                                    | 305  | 0      | 1568  | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _delegates                       | mapping(address => address)                                    | 354  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _checkpoints                     | mapping(address => struct ERC20VotesUpgradeable.Checkpoint[])  | 355  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| _totalSupplyCheckpoints          | struct ERC20VotesUpgradeable.Checkpoint[]                      | 356  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| __gap                            | uint256[47]                                                    | 357  | 0      | 1504  | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| getSharesOf                      | function (address) view returns (uint256)                      | 404  | 0      | 8     | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| getTotalShares                   | function () view returns (uint256)                             | 404  | 8      | 8     | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| pointsPerShare                   | uint256                                                        | 405  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| pointsCorrection                 | mapping(address => int256)                                     | 406  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| withdrawnRewards                 | mapping(address => uint256)                                    | 407  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| __gap                            | uint256[50]                                                    | 408  | 0      | 1600  | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| depositToken                     | contract IERC20Upgradeable                                     | 458  | 0      | 20    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| rewardToken                      | contract IERC20Upgradeable                                     | 459  | 0      | 20    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| escrowPool                       | contract ITimeLockPool                                         | 460  | 0      | 20    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| escrowPortion                    | uint256                                                        | 461  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| escrowDuration                   | uint256                                                        | 462  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| maxBonus                         | uint256                                                        | 463  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| maxLockDuration                  | uint256                                                        | 464  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| curve                            | uint256[]                                                      | 465  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| unit                             | uint256                                                        | 466  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
| depositsOf                       | mapping(address => struct TimeLockPoolUnlocked.Deposit[])      | 467  | 0      | 32    | contracts/TimeLockNonTransferablePoolUnlocked.sol:TimeLockNonTransferablePoolUnlocked |
